workflows:
  android-dev-debug-build: # <--- NUEVO WORKFLOW PARA ANDROID
    name: Android Development Debug Build
    instance_type: linux_x2 # O mac_mini_m1
    max_build_duration: 60
    environment:
      vars:
        ANDROID_FLAVOR: "dev" # Flavor de desarrollo para Android
        ANDROID_ENTRY_POINT: "lib/main_dev.dart" # Punto de entrada para desarrollo
      flutter: stable
      java: 11 # <--- Especificando la versión de JDK. Probar con 8 si 11 sigue dando problemas.
      # cocoapods: default # No es necesario para Android a menos que uses plugins con dependencias nativas de iOS que se resuelven en Android
    cache: # Opcional, pero recomendado para acelerar compilaciones
      cache_paths:
        - $HOME/.gradle/caches
        - $HOME/.gradle/wrapper
        - $FLUTTER_ROOT/.pub-cache
    triggering: # Opcional: configura cuándo se debe ejecutar este workflow
      events:
        - push
      branch_patterns:
        - pattern: "develop" # Por ejemplo, si compilamos desde una rama 'develop'
          include: true
          source: true
        - pattern: "main" # O la rama para desarrollo/pruebas
          include: true
          source: true
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$FLUTTER_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Clean Android project # Opcional, pero puede ayudar con problemas de caché persistentes
        script: |
          cd android && ./gradlew clean && cd ..
      - name: Build Android App Bundle (AAB)
        script: |
          flutter build appbundle \
            --debug \
            --flavor "$ANDROID_FLAVOR" \
            -t "$ANDROID_ENTRY_POINT"
  ios-release:
    name: iOS release
    instance_type: mac_mini_m2
    max_build_duration: 120
    integrations:
      app_store_connect: codemagic
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: io.flutter.app.FlutterApplication
      vars:
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        APP_STORE_APP_ID: 1555555551 # <-- Put the app id number here. This is found in App Store Connect > App > General > App Information
        XCODE_SCHEME: _   # <-- Put Your Xcode scheme here
        BUNDLE_ID: io.flutter.app.FlutterApplication
        ENTRY_POINT: _    # <-- Put Your Entry point to your flutter application here
      flutter: stable
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "main"
          include: true
          source: true
    scripts:
      - name: Get Flutter Packages
        script: |
          flutter packages pub get
      - name: Pod install
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Flutter build ipa and automatic versioning
        script: |
          flutter build ipa --release \
          --build-name=1.0.0 \
          --build-number=$(($(app-store-connect get-latest-testflight-build-number "$APP_STORE_ID") + 1)) \
          --export-options-plist=/Users/builder/export_options.plist \
          --flavor="$XCODE_SCHEME" \
          -t "$ENTRY_POINT"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      email:
        recipients:
          - user_1@example.com
          - user_2@example.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        
        # Configuration related to TestFlight (optional)
        # Note: This action is performed during post-processing.
        submit_to_testflight: true
        beta_groups: # Specify the names of beta tester groups that will get access to the build once it has passed beta review.
          - group name 1
          - group name 2

        # Configuration related to App Store (optional)
        # Note: This action is performed during post-processing.
        submit_to_app_store: false
